### ISSUE TITLE
Live tweeting issue

### ISSUE THREAD

**Issue by webRat** [corylanou/go-meetup#18]
The example given:
https://twitter.com/corylanou/status/691799977094451202

`@varunksaini presenting Writing an HTTPS Server in #golang at @ChicagoGolang hosted by @MediaMath`

This isn't a good example. You basically directed a message to `@varunksaini`. The general twittersphere (those people not using the website) might have seen it, but those people using the website will never see it unless they go to your `Tweets & replies` tab, which, most rarely do.

A better example:
`.@varunksaini presenting Writing an HTTPS Server in #golang at @ChicagoGolang hosted by @MediaMath`

Note the leading `.` in front of `@varunksaini` - That prevents it from being a directed tweet.

Hope this helps.

**Comment by corylanou** [comment]
Thanks!
